// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGzp0DFFH7YEpX8yaDL8DNzSEqSKKAp9w',
    appId: '1:40578572044:web:e650873dca725a1d14b329',
    messagingSenderId: '40578572044',
    projectId: 'vangolk-30026',
    authDomain: 'vangolk-30026.firebaseapp.com',
    storageBucket: 'vangolk-30026.firebasestorage.app',
    measurementId: 'G-1QYTFZPRSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8vmSgG-G4YU62fTf6rsO6XvXdJqoNK7E',
    appId: '1:40578572044:android:54dd70affa88fa9314b329',
    messagingSenderId: '40578572044',
    projectId: 'vangolk-30026',
    storageBucket: 'vangolk-30026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAml1FaXzCqDOgvMBiOEgG5SmRdAA3QXPM',
    appId: '1:40578572044:ios:3e02f2306ba8fa6214b329',
    messagingSenderId: '40578572044',
    projectId: 'vangolk-30026',
    storageBucket: 'vangolk-30026.firebasestorage.app',
    androidClientId: '40578572044-8f9dgjvf74r72msl37ocg3gct0ntf43s.apps.googleusercontent.com',
    iosClientId: '40578572044-5i9f9kmo6lc0b529vjitf3qrvchpo2qu.apps.googleusercontent.com',
    iosBundleId: 'com.vango.parent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXG3LyGuRd0RdBV4s5XMx9qC4fEe0p_x0',
    appId: '1:40578572044:ios:f2a82d30febd9d6414b329',
    messagingSenderId: '40578572044',
    projectId: 'vangolk-30026',
    storageBucket: 'vangolk-30026.firebasestorage.app',
    androidClientId: '40578572044-8f9dgjvf74r72msl37ocg3gct0ntf43s.apps.googleusercontent.com',
    iosClientId: '40578572044-nvrr8pbfsg1lhmdf5ir00pifjr3u9hod.apps.googleusercontent.com',
    iosBundleId: 'com.example.vangoDriverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGzp0DFFH7YEpX8yaDL8DNzSEqSKKAp9w',
    appId: '1:40578572044:web:aacc8f521d69260714b329',
    messagingSenderId: '40578572044',
    projectId: 'vangolk-30026',
    authDomain: 'vangolk-30026.firebaseapp.com',
    storageBucket: 'vangolk-30026.firebasestorage.app',
    measurementId: 'G-LYV7F2X8S3',
  );
}
